name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch:      # allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate github-contribution-grid-snake.svg

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: Ncoder23
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      - name: Commit & Push the snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Generate GitHub contribution snake"
          git push
